import { useMemo, useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Pencil, Palette } from "lucide-react";
import EditToolDialog from "./EditToolDialog";
import type { MCPConnectionConfig } from "@/lib/mcp_client";

export type EndpointType = "mcp" | "api" | "script" | "webhook" | "integration";

export type MCPEndpointConfig = MCPConnectionConfig;

export interface APIEndpointConfig {
  endpoint: string;
  method?: string;
  timeout?: number;
  headers?: Record<string, string>;
  [key: string]: any;
}

export interface Tool {
  id: string; // hex ID generated by backend
  toolId: string; // same as id, for consistency
  name: string;
  description: string;
  endpointType: EndpointType;
  endpointConfig: MCPEndpointConfig | APIEndpointConfig;
  status?: "active" | "disabled";
  // Legacy field for backward compatibility
  type?: "api" | "script" | "webhook" | "integration" | "mcp";
  // Tool input/output schemas (JSON Schema format)
  inputSchema?: Record<string, any> | null;
  outputSchema?: Record<string, any> | null;
}

interface ToolsListProps {
  tools: Tool[];
  showFilters?: boolean;
  selectable?: boolean;
  onSelectionChange?: (selectedIds: string[]) => void;
  importButton?: React.ReactNode;
  onToolUpdate?: (tool: Tool) => void;
  onToolDelete?: (toolId: string) => void;
  showEditButton?: boolean;
  onEditUX?: (tool: Tool) => void;
  projectId?: string;
}

const ToolsList = ({
  tools,
  showFilters = true,
  selectable = false,
  onSelectionChange,
  importButton,
  onToolUpdate,
  onToolDelete,
  showEditButton = true,
  onEditUX,
  projectId,
}: ToolsListProps) => {
  const [query, setQuery] = useState("");
  const [typeFilter, setTypeFilter] = useState<string>("all");
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [editingTool, setEditingTool] = useState<Tool | null>(null);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);

  const filteredTools = useMemo(() => {
    const q = query.trim().toLowerCase();
    return tools.filter((tool) => {
      const matchesQuery = !q || 
        tool.name.toLowerCase().includes(q) ||
        tool.description.toLowerCase().includes(q);
      const toolType = tool.endpointType || tool.type || "all";
      const matchesType = typeFilter === "all" || toolType === typeFilter;
      return matchesQuery && matchesType;
    });
  }, [query, typeFilter, tools]);

  const handleEditClick = (tool: Tool) => {
    setEditingTool(tool);
    setIsEditDialogOpen(true);
  };

  const handleToolUpdate = (updatedTool: Tool) => {
    if (onToolUpdate) {
      onToolUpdate(updatedTool);
    }
  };

  useEffect(() => {
    if (onSelectionChange) {
      // Only return IDs that exist in current tools
      const validIds = Array.from(selectedIds).filter(id => 
        tools.some(t => t.id === id)
      );
      onSelectionChange(validIds);
    }
  }, [selectedIds, onSelectionChange, tools]);

  const toggleSelectAll = () => {
    if (selectedIds.size === filteredTools.length) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(filteredTools.map(t => t.id)));
    }
  };

  const toggleTool = (toolId: string) => {
    const newSelected = new Set(selectedIds);
    if (newSelected.has(toolId)) {
      newSelected.delete(toolId);
    } else {
      newSelected.add(toolId);
    }
    setSelectedIds(newSelected);
  };

  const allSelected = filteredTools.length > 0 && selectedIds.size === filteredTools.length;
  const someSelected = selectedIds.size > 0 && selectedIds.size < filteredTools.length;

  return (
    <div className="space-y-8">
      {showFilters && (
        <div className="flex items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="w-72 relative">
              <Input
                id="tool-search"
                placeholder="Search tools..."
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                className="pr-10"
              />
              {query && (
                <button
                  onClick={() => setQuery("")}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                  aria-label="Clear search"
                >
                  ×
                </button>
              )}
            </div>
            <div className="w-52">
              <Select value={typeFilter} onValueChange={setTypeFilter}>
                <SelectTrigger>
                  <SelectValue placeholder="All" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All</SelectItem>
                  <SelectItem value="api">API</SelectItem>
                  <SelectItem value="script">Script</SelectItem>
                  <SelectItem value="webhook">Webhook</SelectItem>
                  <SelectItem value="integration">Integration</SelectItem>
                  <SelectItem value="mcp">MCP</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          {importButton && (
            <div>
              {importButton}
            </div>
          )}
        </div>
      )}

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardDescription>Showing {filteredTools.length} of {tools.length}</CardDescription>
            {selectable && filteredTools.length > 0 && (
              <Button
                variant="outline"
                size="sm"
                onClick={toggleSelectAll}
              >
                {allSelected ? "Deselect All" : someSelected ? "Select All" : "Select All"}
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredTools.map((tool) => (
              <Card key={tool.id} className={`${selectable ? "relative" : ""} group cursor-pointer transition-all duration-200 hover:scale-[1.02] min-w-0 overflow-hidden`}>
                {selectable && (
                  <div className="absolute top-4 left-4 z-10">
                    <Checkbox
                      checked={selectedIds.has(tool.id)}
                      onCheckedChange={() => toggleTool(tool.id)}
                    />
                  </div>
                )}
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between gap-3">
                    <div className={`flex-1 min-w-0 ${selectable ? "pl-10" : ""}`}>
                      <CardTitle className="text-lg font-semibold mb-1.5 group-hover:text-primary transition-colors truncate">
                        {tool.name}
                      </CardTitle>
                      <CardDescription className="capitalize text-xs font-medium">
                        {(tool.endpointType || tool.type || "unknown")}
                      </CardDescription>
                    </div>
                    <div className="flex items-start gap-2 shrink-0">
                      {tool.status && (
                        <Badge 
                          variant={tool.status === "active" ? "success" : "secondary"}
                          className="rounded-full text-xs px-3 py-1 flex items-center gap-1.5"
                        >
                          {tool.status === "active" && (
                            <span className="relative flex h-1.5 w-1.5">
                              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-white/80 opacity-75" />
                              <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-white" />
                            </span>
                          )}
                          {tool.status}
                        </Badge>
                      )}
                      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                        {showEditButton && onToolUpdate && (
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 hover:bg-primary/10 hover:text-primary"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleEditClick(tool);
                            }}
                            title="Edit Tool"
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                        )}
                        {onEditUX && (
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 hover:bg-primary/10 hover:text-primary"
                            onClick={(e) => {
                              e.stopPropagation();
                              onEditUX(tool);
                            }}
                            title="Edit UX"
                          >
                            <Palette className="h-4 w-4" />
                          </Button>
                        )}
                      </div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="pt-0">
                  <p className="text-sm text-muted-foreground leading-relaxed line-clamp-3 break-words">
                    {tool.description}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>

      {onToolUpdate && (
        <EditToolDialog
          tool={editingTool}
          open={isEditDialogOpen}
          onOpenChange={setIsEditDialogOpen}
          onSave={handleToolUpdate}
          onDelete={onToolDelete}
          projectId={projectId}
        />
      )}
    </div>
  );
};

export default ToolsList;

